<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="4.0">
  <Target
    Name="MacBundle_GenerateBundleAfterBuild"
    AfterTargets="Build"
    Condition="$(GenerateMacOSBundle)"
  >
    <PropertyGroup>
      <MacOSBundleName Condition="'$(MacOSBundleName)' == ''">$(Product)</MacOSBundleName>
      <MacOSBundleName Condition="'$(MacOSBundleName)' == ''">$(AssemblyName)</MacOSBundleName>
      <MacOSBundleCopyright Condition="'$(MacOSBundleCopyright)' == ''"
        >$(Copyright)</MacOSBundleCopyright
      >
      <MacOSBundleVersion Condition="'$(MacOSBundleVersion)' == ''">$(Version)</MacOSBundleVersion>
      <MacOSBundleIcon Condition="'$(MacOSBundleIcon)' == ''">$(ApplicationIcon)</MacOSBundleIcon>
    </PropertyGroup>

    <BundleTask
      BundleIdentifier="$(MacOSBundleIdentifier)"
      BundleName="$(MacOSBundleName)"
      BundleDisplayName="$(MacOSBundleDisplayName)"
      BundleSpokenName="$(MacOSBundleSpokenName)"
      BundleCopyright="$(MacOSBundleCopyright)"
      BundleVersion="$(MacOSBundleVersion)"
      BundleShortVersion="$(MacOSBundleShortVersion)"
      BundleIconFilePath="$(MacOSBundleIcon)"
      TargetFilePath="$(TargetPath)"
    />
  </Target>

  <Target
    Name="MacBundle_GenerateBundleAfterPublish"
    AfterTargets="Publish"
    Condition="$(GenerateMacOSBundle)"
  >
    <PropertyGroup>
      <MacOSBundleName Condition="'$(MacOSBundleName)' == ''">$(Product)</MacOSBundleName>
      <MacOSBundleName Condition="'$(MacOSBundleName)' == ''">$(AssemblyName)</MacOSBundleName>
      <MacOSBundleCopyright Condition="'$(MacOSBundleCopyright)' == ''"
        >$(Copyright)</MacOSBundleCopyright
      >
      <MacOSBundleVersion Condition="'$(MacOSBundleVersion)' == ''">$(Version)</MacOSBundleVersion>
      <MacOSBundleIcon Condition="'$(MacOSBundleIcon)' == ''">$(ApplicationIcon)</MacOSBundleIcon>
    </PropertyGroup>

    <BundleTask
      BundleIdentifier="$(MacOSBundleIdentifier)"
      BundleName="$(MacOSBundleName)"
      BundleDisplayName="$(MacOSBundleDisplayName)"
      BundleSpokenName="$(MacOSBundleSpokenName)"
      BundleCopyright="$(MacOSBundleCopyright)"
      BundleVersion="$(MacOSBundleVersion)"
      BundleShortVersion="$(MacOSBundleShortVersion)"
      BundleIconFilePath="$(MacOSBundleIcon)"
      TargetFilePath="$([System.IO.Path]::Combine('$(ProjectDir)', '$(PublishDir)/$(AssemblyName).dll'))"
    />
  </Target>
</Project>
