<Project
  xmlns="http://schemas.microsoft.com/developer/msbuild/2003"
  ToolsVersion="4.0"
  TreatAsLocalProperty="TaskAssembly"
>
  <PropertyGroup>
    <GenerateMacOSBundle
      Condition="'$(GenerateMacOSBundle)' == '' and ($(RuntimeIdentifier.ToLowerInvariant().StartsWith('osx')) or ('$(RuntimeIdentifier)' == '' and $([MSBuild]::IsOsPlatform('OSX'))))"
      >true</GenerateMacOSBundle
    >
    <GenerateMacOSBundle Condition="'$(GenerateMacOSBundle)' == ''">false</GenerateMacOSBundle>
  </PropertyGroup>

  <PropertyGroup>
    <TaskAssembly Condition="'$(MSBuildRuntimeType)' == 'Core'"
      >$(MSBuildThisFileDirectory)/../tasks/netstandard2.0/MacBundle.dll</TaskAssembly
    >
    <TaskAssembly Condition="'$(MSBuildRuntimeType)' != 'Core'"
      >$(MSBuildThisFileDirectory)/../tasks/net472/MacBundle.dll</TaskAssembly
    >
  </PropertyGroup>

  <UsingTask TaskName="MacBundle.BundleTask" AssemblyFile="$(TaskAssembly)" />
</Project>
