<Project
  xmlns="http://schemas.microsoft.com/developer/msbuild/2003"
  ToolsVersion="4.0"
  TreatAsLocalProperty="TaskAssembly"
>
  <Import Project="MacBundle.props" />

  <!-- Props for local testing, used by the demo project -->
  <PropertyGroup>
    <TaskAssembly
      >$(MSBuildThisFileDirectory)/bin/$(Configuration)/netstandard2.0/MacBundle.dll</TaskAssembly
    >
  </PropertyGroup>
</Project>
